{% set name = "gnuconfig" %}
{% set version = "2021.05.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Updated to the latest version of the package where the version number is the date of the commit.
  # The git_rev is the commit hash.
  git_url: https://git.savannah.gnu.org/r/config.git
  git_rev: 4550d2f15b3a7ce2451c1f29500b9339430c877f

build:
  noarch: generic
  number: 0
  script: |
    mkdir -p $PREFIX/share/gnuconfig
    cp config.sub $PREFIX/share/gnuconfig/config.sub
    cp config.guess $PREFIX/share/gnuconfig/config.guess

test:
  commands:
    - test -f $PREFIX/share/gnuconfig/config.sub
    - test -f $PREFIX/share/gnuconfig/config.guess

about:
  home: https://savannah.gnu.org/projects/config/
  license: GPL-3.0-or-later WITH Autoconf-exception-2.0
  license_file: LICENSE.txt
  summary: 'Updated config.sub and config.guess file from GNU'

extra:
  recipe-maintainers:
    - isuruf
